### ISSUE TITLE
TagManager breaks backoffice Log Viewer styling

### ISSUE THREAD

**Issue by bowserm** [usome/UmbracoTagManager#16]
# The Problem
I'm using TagManager 1.0.4 on Umbraco 13.5.0. I noticed that when I use the built in "Log Viewer" in the Settings section of Umbraco, the svg for the search magnifying glass is huge and has `position: absolute;`.

![logviewer_broken_styles](https://github.com/user-attachments/assets/e60a3413-5881-4972-83d0-d00addf75f92)

This appears to be the result of the `/App_Plugins/TagManager/backoffice/TagManagerTree/TagManager.css` file not being specific enough with its styles.

The following CSS is from `/App_Plugins/TagManager/backoffice/TagManagerTree/TagManager.css` and is responsible for the broken styles on the Umbraco Log Viewer.

```css
.icon-search {
    position: absolute;
    color: #1b264f;
    top: 0;
    right: 0;
    margin: 20px;
    margin-bottom: 20px;
    transition: background-color 0.3s ease;
}


    .icon-search.active input {
        width: 200px;
        transition: background-color 0.3s ease;
        color: #1b264f;
    }
```

# Proposed Solution
Make sure that there is a wrapper class on all of the html used in the backoffice "Tag Manager" section of the site. Then make sure that the CSS selectors are all scoped under that class, so it can't ever affect the rest of the Umbraco backoffice. For example:

```html
<div ng-controller="TagManager.TagDisplayController" ng-class="getSelectedTagsContainerClass()" class="usome-tagmanager">
    <umb-box-header title="Tag Manager"></umb-box-header>
    ...
```

```css
.usome-tagmanager .icon-search {
    position: absolute;
    color: #1b264f;
    top: 0;
    right: 0;
    margin: 20px;
    margin-bottom: 20px;
    transition: background-color 0.3s ease;
}


    .usome-tagmanager .icon-search.active input {
        width: 200px;
        transition: background-color 0.3s ease;
        color: #1b264f;
    }
```
